import { browser } from '$app/environment';

export function setupCopyButtons() {
	if (!browser) return;

	const preBlocks = document.querySelectorAll('.prose pre');

	preBlocks.forEach((pre) => {
		// Prevent adding multiple buttons if setup is called multiple times
		if (pre.parentElement?.classList.contains('code-block-wrapper')) return;

		// Create a wrapper
		const wrapper = document.createElement('div');
		wrapper.className = 'code-block-wrapper';

		// Wrap the pre block
		pre.parentNode?.insertBefore(wrapper, pre);
		wrapper.appendChild(pre);

		// Wrap code lines to allow line-level hover styling
		const codeEl = pre.querySelector('code');
		if (codeEl && !codeEl.classList.contains('lines-wrapped')) {
			const html = codeEl.innerHTML;
			const lines = html.split('\n');
			if (lines.length > 0 && lines[lines.length - 1] === '') {
				lines.pop(); // Remove trailing empty line often generated by mdsvex
			}
			codeEl.innerHTML = lines
				.map((line) => `<span class="code-line">${line || ' '}</span>`)
				.join('\n');
			codeEl.classList.add('lines-wrapped');
		}

		// Create the copy button
		const btn = document.createElement('button');
		btn.className = 'copy-btn';
		btn.innerHTML = `
            <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">
                <rect x="9" y="9" width="13" height="13" rx="2" ry="2"></rect>
                <path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"></path>
            </svg>
        `;
		btn.setAttribute('aria-label', 'Copy code to clipboard');

		btn.addEventListener('click', async () => {
			const codeEl = pre.querySelector('code');
			const codeText = codeEl ? codeEl.innerText : (pre as HTMLElement).innerText;

			try {
				await navigator.clipboard.writeText(codeText);
				btn.innerHTML = `
                    <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">
                        <polyline points="20 6 9 17 4 12"></polyline>
                    </svg>
                `;
				btn.classList.add('copied');

				setTimeout(() => {
					btn.innerHTML = `
                        <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">
                            <rect x="9" y="9" width="13" height="13" rx="2" ry="2"></rect>
                            <path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"></path>
                        </svg>
                    `;
					btn.classList.remove('copied');
				}, 2000);
			} catch (err) {
				console.error('Failed to copy text', err);
			}
		});

		wrapper.appendChild(btn);
	});
}
