import{a as i,f as l}from"./D-F4TtMm.js";import{u as n,v as r,w as e,q as c}from"./CX7hlXOH.js";import{h as o}from"./BRDHV1Tp.js";const u={title:"Welcome to Blueprint",date:"2026-03-26T00:00:00.000Z",description:"An introduction to this blog — what it is, why it exists, and where it's heading.",tags:["auto","hardware","complex"],author:"Blueprint",published:!0},{title:k,date:w,description:f,tags:b,author:y,published:v}=u;var d=l('<h1>Welcome to Blueprint</h1> <p>This is the first post on <strong>Blueprint</strong> — a minimal, fast, and focused blog built with SvelteKit and powered by plain markdown files.</p> <h2>Why Another Blog?</h2> <p>Good question. The short answer: writing is thinking made visible. Having a place to document ideas, experiments, and lessons learned forces clarity. Blueprint is that place.</p> <h2>What You’ll Find Here</h2> <ul><li><strong>Engineering breakdowns</strong> — deep-dives into how things are built</li> <li><strong>Robotics & embedded systems</strong> — the physical side of software</li> <li><strong>Short essays</strong> — ideas worth exploring</li></ul> <h2>How It’s Built</h2> <p>The entire site is built with <a href="https://kit.svelte.dev" rel="nofollow">SvelteKit</a> — a full-stack framework built around Svelte. Posts are written in markdown and processed through <strong>MDsveX</strong>, which compiles <code>.md</code> files into Svelte components at build time.</p> <pre class="language-ts"></pre> <p>The result is blazing-fast static pages with zero JavaScript runtime cost per post.</p> <h2>Adding Your Own Posts</h2> <p>Drop any <code>.md</code> file into <code>src/posts/</code> with this frontmatter:</p> <pre class="language-markdown"></pre> <p>The route <code>/blog/my-post-title</code> will be live automatically.</p> <hr/> <p>That’s it for now. Stay tuned — more posts are on the way.</p>',1);function T(p){var s=d(),t=n(r(s),16);o(t,()=>`<code class="language-ts"><span class="token comment">// A post loads like this:</span>
<span class="token keyword">const</span> post <span class="token operator">=</span> <span class="token keyword">await</span> <span class="token keyword">import</span><span class="token punctuation">(</span><span class="token template-string"><span class="token template-punctuation string">&#96;</span><span class="token string">../../../posts/</span><span class="token interpolation"><span class="token interpolation-punctuation punctuation">$&#123;</span>params<span class="token punctuation">.</span>slug<span class="token interpolation-punctuation punctuation">&#125;</span></span><span class="token string">.md</span><span class="token template-punctuation string">&#96;</span></span><span class="token punctuation">)</span><span class="token punctuation">;</span>
<span class="token keyword">return</span> <span class="token punctuation">&#123;</span>
  content<span class="token operator">:</span> post<span class="token punctuation">.</span>default<span class="token punctuation">,</span>
  meta<span class="token operator">:</span> post<span class="token punctuation">.</span>metadata
<span class="token punctuation">&#125;</span><span class="token punctuation">;</span></code>`,!0),e(t);var a=n(t,8);o(a,()=>`<code class="language-markdown"><span class="token front-matter-block"><span class="token punctuation">---</span>
<span class="token front-matter yaml language-yaml">title: My Post Title
date: 2026-03-26
description: Describe what the post is about.
tags: [svelte, web]
author: Your Name
published: true</span>
<span class="token punctuation">---</span></span></code>`,!0),e(a),c(6),i(p,s)}export{T as default,u as metadata};
