import{a as r,f as l}from"./DQlmh0hR.js";import{ac as s,ad as u,ae as t}from"./C84eEptJ.js";import{h as o}from"./BGhWtArZ.js";const i={title:"Mecanum Drivetrain",date:"2026-03-28T00:00:00.000Z",description:"Programming and optimizing a 4-wheel mecanum drivetrain for FTC.",tags:["software","beginner","drivetrain"],author:"Ishaan Desai",published:!0},{title:g,date:f,description:w,tags:b,author:y,published:v}=i;var k=l('<p>Mecanum wheels are unique in that they use 45-degree rollers to generate forces in different directions. By changing the speed and direction of the four motors, your robot can move in any direction (strafing) and rotate simultaneously.</p> <h2>Mecanum Vectoring</h2> <p>The most important thing to understand is how the wheels combine to create movement:</p> <ul><li><strong>Forward:</strong> All 4 wheels forward.</li> <li><strong>Strafe Left:</strong> Front-Right and Back-Left forward, Front-Left and Back-Right backward.</li> <li><strong>Turn Left:</strong> Right side forward, left side backward.</li></ul> <hr/> <h2>Robocentric Driving</h2> <p>In Robocentric driving, the robot moves relative to its own front. Pushing the stick forward always makes the robot go where its nose is pointing.</p> <h3>The Equations:</h3> <pre class="language-java"></pre> <hr/> <h2>Field Centric Driving</h2> <p>Field Centric driving makes the robot move relative to the <strong>field</strong>, not itself. Pushing forward on the stick will make the robot move away from you, regardless of which way it is facing.</p> <h3>Why use Field Centric?</h3> <ul><li><strong>Easier for Drivers:</strong> No need to compensate for the robot’s orientation.</li> <li><strong>Consistent Control:</strong> The robot always behaves the same way relative to the driver’s perspective.</li></ul> <h3>The Implementation (using IMU):</h3> <pre class="language-java"></pre> <h2>Standard Drive Functions</h2> <p>When programming your drivetrain, ensure you normalize the motor powers so that no single value exceeds 1.0, which would cause inconsistent movements.</p> <pre class="language-java"></pre>',1);function x(c){var p=k(),n=s(u(p),16);o(n,()=>`<code class="language-java"><span class="token keyword">double</span> y <span class="token operator">=</span> <span class="token operator">-</span>gamepad1<span class="token punctuation">.</span>left_stick_y<span class="token punctuation">;</span> <span class="token comment">// Straight power</span>
<span class="token keyword">double</span> x <span class="token operator">=</span> gamepad1<span class="token punctuation">.</span>left_stick_x<span class="token punctuation">;</span>  <span class="token comment">// Strafe power</span>
<span class="token keyword">double</span> rx <span class="token operator">=</span> gamepad1<span class="token punctuation">.</span>right_stick_x<span class="token punctuation">;</span> <span class="token comment">// Rotation power</span>

<span class="token comment">// Calculate wheel powers</span>
<span class="token keyword">double</span> frontLeftPower <span class="token operator">=</span> y <span class="token operator">+</span> x <span class="token operator">+</span> rx<span class="token punctuation">;</span>
<span class="token keyword">double</span> backLeftPower <span class="token operator">=</span> y <span class="token operator">-</span> x <span class="token operator">+</span> rx<span class="token punctuation">;</span>
<span class="token keyword">double</span> frontRightPower <span class="token operator">=</span> y <span class="token operator">-</span> x <span class="token operator">-</span> rx<span class="token punctuation">;</span>
<span class="token keyword">double</span> backRightPower <span class="token operator">=</span> y <span class="token operator">+</span> x <span class="token operator">-</span> rx<span class="token punctuation">;</span></code>`,!0),t(n);var a=s(n,14);o(a,()=>`<code class="language-java"><span class="token comment">// Read the robot's heading from the IMU</span>
<span class="token keyword">double</span> botHeading <span class="token operator">=</span> imu<span class="token punctuation">.</span><span class="token function">getRobotYawPitchRollAngles</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">.</span><span class="token function">getYaw</span><span class="token punctuation">(</span><span class="token class-name">AngleUnit</span><span class="token punctuation">.</span><span class="token constant">RADIANS</span><span class="token punctuation">)</span><span class="token punctuation">;</span>

<span class="token comment">// Rotate the input vector by the negative of the robot's heading</span>
<span class="token keyword">double</span> rotX <span class="token operator">=</span> x <span class="token operator">*</span> <span class="token class-name">Math</span><span class="token punctuation">.</span><span class="token function">cos</span><span class="token punctuation">(</span><span class="token operator">-</span>botHeading<span class="token punctuation">)</span> <span class="token operator">-</span> y <span class="token operator">*</span> <span class="token class-name">Math</span><span class="token punctuation">.</span><span class="token function">sin</span><span class="token punctuation">(</span><span class="token operator">-</span>botHeading<span class="token punctuation">)</span><span class="token punctuation">;</span>
<span class="token keyword">double</span> rotY <span class="token operator">=</span> x <span class="token operator">*</span> <span class="token class-name">Math</span><span class="token punctuation">.</span><span class="token function">sin</span><span class="token punctuation">(</span><span class="token operator">-</span>botHeading<span class="token punctuation">)</span> <span class="token operator">+</span> y <span class="token operator">*</span> <span class="token class-name">Math</span><span class="token punctuation">.</span><span class="token function">cos</span><span class="token punctuation">(</span><span class="token operator">-</span>botHeading<span class="token punctuation">)</span><span class="token punctuation">;</span>

<span class="token comment">// Now apply the rotated powers (rotX and rotY) instead of raw x and y</span>
<span class="token keyword">double</span> fl <span class="token operator">=</span> rotY <span class="token operator">+</span> rotX <span class="token operator">+</span> rx<span class="token punctuation">;</span>
<span class="token keyword">double</span> bl <span class="token operator">=</span> rotY <span class="token operator">-</span> rotX <span class="token operator">+</span> rx<span class="token punctuation">;</span>
<span class="token keyword">double</span> fr <span class="token operator">=</span> rotY <span class="token operator">-</span> rotX <span class="token operator">-</span> rx<span class="token punctuation">;</span>
<span class="token keyword">double</span> br <span class="token operator">=</span> rotY <span class="token operator">+</span> rotX <span class="token operator">-</span> rx<span class="token punctuation">;</span></code>`,!0),t(a);var e=s(a,6);o(e,()=>`<code class="language-java"><span class="token comment">// Find the maximum value among the four powers</span>
<span class="token keyword">double</span> max <span class="token operator">=</span> <span class="token class-name">Math</span><span class="token punctuation">.</span><span class="token function">max</span><span class="token punctuation">(</span><span class="token class-name">Math</span><span class="token punctuation">.</span><span class="token function">abs</span><span class="token punctuation">(</span>fl<span class="token punctuation">)</span><span class="token punctuation">,</span> <span class="token class-name">Math</span><span class="token punctuation">.</span><span class="token function">max</span><span class="token punctuation">(</span><span class="token class-name">Math</span><span class="token punctuation">.</span><span class="token function">abs</span><span class="token punctuation">(</span>bl<span class="token punctuation">)</span><span class="token punctuation">,</span> 
             <span class="token class-name">Math</span><span class="token punctuation">.</span><span class="token function">max</span><span class="token punctuation">(</span><span class="token class-name">Math</span><span class="token punctuation">.</span><span class="token function">abs</span><span class="token punctuation">(</span>fr<span class="token punctuation">)</span><span class="token punctuation">,</span> <span class="token class-name">Math</span><span class="token punctuation">.</span><span class="token function">abs</span><span class="token punctuation">(</span>br<span class="token punctuation">)</span><span class="token punctuation">)</span><span class="token punctuation">)</span><span class="token punctuation">)</span><span class="token punctuation">;</span>

<span class="token comment">// If the max is greater than 1.0, scale them all down</span>
<span class="token keyword">if</span> <span class="token punctuation">(</span>max <span class="token operator">></span> <span class="token number">1.0</span><span class="token punctuation">)</span> <span class="token punctuation">&#123;</span>
    fl <span class="token operator">/=</span> max<span class="token punctuation">;</span>
    bl <span class="token operator">/=</span> max<span class="token punctuation">;</span>
    fr <span class="token operator">/=</span> max<span class="token punctuation">;</span>
    br <span class="token operator">/=</span> max<span class="token punctuation">;</span>
<span class="token punctuation">&#125;</span>

<span class="token comment">// Apply the powers to the motors</span>
frontLeft<span class="token punctuation">.</span><span class="token function">setPower</span><span class="token punctuation">(</span>fl<span class="token punctuation">)</span><span class="token punctuation">;</span>
backLeft<span class="token punctuation">.</span><span class="token function">setPower</span><span class="token punctuation">(</span>bl<span class="token punctuation">)</span><span class="token punctuation">;</span>
frontRight<span class="token punctuation">.</span><span class="token function">setPower</span><span class="token punctuation">(</span>fr<span class="token punctuation">)</span><span class="token punctuation">;</span>
backRight<span class="token punctuation">.</span><span class="token function">setPower</span><span class="token punctuation">(</span>br<span class="token punctuation">)</span><span class="token punctuation">;</span></code>`,!0),t(e),r(c,p)}export{x as default,i as metadata};
