import{a as i,f as u}from"./CzTkM99v.js";import{q as n,u as d,v as a,w as k}from"./D7a__486.js";import{h as s}from"./PSLx_Rl1.js";const h={title:"Writing in Markdown — A Quick Reference",date:"2026-03-20T00:00:00.000Z",description:"A practical guide to markdown syntax — headings, code blocks, tables, blockquotes, and more.",tags:["software","hardware","auto","easy"],author:"Blueprint",published:!0},{title:w,date:y,description:C,tags:v,author:x,published:H}=h;var g=u('<h1>Writing in Markdown — A Quick Reference</h1> <p>Markdown is plain text that renders as formatted HTML. It’s fast to write, easy to read, and version-control friendly. Here’s a reference for everything you need.</p> <h2>Headings</h2> <pre class="language-markdown"></pre> <h2>Text Formatting</h2> <table><thead><tr><th>Syntax</th><th>Result</th></tr></thead><tbody><tr><td><code>**bold**</code></td><td><strong>bold</strong></td></tr><tr><td><code>*italic*</code></td><td><em>italic</em></td></tr><tr><td><code>`inline code`</code></td><td><code>inline code</code></td></tr><tr><td><code>~~strikethrough~~</code></td><td><del>strikethrough</del></td></tr></tbody></table> <h2>Lists</h2> <p><strong>Unordered:</strong></p> <ul><li>Item one</li> <li>Item two <ul><li>Nested item</li> <li>Another nested item</li></ul></li></ul> <p><strong>Ordered:</strong></p> <ol><li>First step</li> <li>Second step</li> <li>Third step</li></ol> <h2>Code Blocks</h2> <p>Fenced code blocks with language tags support syntax highlighting:</p> <pre class="language-javascript"></pre> <pre class="language-python"></pre> <h2>Blockquotes</h2> <blockquote><p>“The best writing is rewriting.”\n— E.B. White</p></blockquote> <p>Blockquotes are useful for callouts, quotes, or emphasis.</p> <h2>Links and Images</h2> <pre class="language-markdown"></pre> <h2>Horizontal Rules</h2> <p>Use <code>---</code> to create a thematic break:</p> <hr/> <h2>Tables</h2> <pre class="language-markdown"></pre> <p>Renders as:</p> <table><thead><tr><th>Column A</th><th>Column B</th><th>Column C</th></tr></thead><tbody><tr><td>Cell 1</td><td>Cell 2</td><td>Cell 3</td></tr><tr><td>Cell 4</td><td>Cell 5</td><td>Cell 6</td></tr></tbody></table> <hr/> <p>That covers 95% of what you’ll ever need. Now go write something.</p>',1);function _(r){var l=g(),t=n(d(l),6);s(t,()=>`<code class="language-markdown"><span class="token title important"><span class="token punctuation">#</span> H1 — Page title</span>
<span class="token title important"><span class="token punctuation">##</span> H2 — Section</span>
<span class="token title important"><span class="token punctuation">###</span> H3 — Subsection</span>
<span class="token title important"><span class="token punctuation">####</span> H4 — Detail</span></code>`,!0),a(t);var e=n(t,20);s(e,()=>`<code class="language-javascript"><span class="token keyword">function</span> <span class="token function">greet</span><span class="token punctuation">(</span><span class="token parameter">name</span><span class="token punctuation">)</span> <span class="token punctuation">&#123;</span>
  <span class="token keyword">return</span> <span class="token template-string"><span class="token template-punctuation string">&#96;</span><span class="token string">Hello, </span><span class="token interpolation"><span class="token interpolation-punctuation punctuation">$&#123;</span>name<span class="token interpolation-punctuation punctuation">&#125;</span></span><span class="token string">!</span><span class="token template-punctuation string">&#96;</span></span><span class="token punctuation">;</span>
<span class="token punctuation">&#125;</span>

console<span class="token punctuation">.</span><span class="token function">log</span><span class="token punctuation">(</span><span class="token function">greet</span><span class="token punctuation">(</span><span class="token string">'World'</span><span class="token punctuation">)</span><span class="token punctuation">)</span><span class="token punctuation">;</span></code>`,!0),a(e);var o=n(e,2);s(o,()=>`<code class="language-python"><span class="token keyword">def</span> <span class="token function">fibonacci</span><span class="token punctuation">(</span>n<span class="token punctuation">)</span><span class="token punctuation">:</span>
    <span class="token keyword">if</span> n <span class="token operator">&lt;=</span> <span class="token number">1</span><span class="token punctuation">:</span>
        <span class="token keyword">return</span> n
    <span class="token keyword">return</span> fibonacci<span class="token punctuation">(</span>n <span class="token operator">-</span> <span class="token number">1</span><span class="token punctuation">)</span> <span class="token operator">+</span> fibonacci<span class="token punctuation">(</span>n <span class="token operator">-</span> <span class="token number">2</span><span class="token punctuation">)</span></code>`,!0),a(o);var p=n(o,10);s(p,()=>`<code class="language-markdown"><span class="token url">[<span class="token content">Link text</span>](<span class="token url">https://example.com</span>)</span>
<span class="token url"><span class="token operator">!</span>[<span class="token content">Alt text</span>](<span class="token url">./image.png</span>)</span></code>`,!0),a(p);var c=n(p,10);s(c,()=>`<code class="language-markdown"><span class="token table"><span class="token table-header-row"><span class="token punctuation">|</span><span class="token table-header important"> Column A </span><span class="token punctuation">|</span><span class="token table-header important"> Column B </span><span class="token punctuation">|</span><span class="token table-header important"> Column C </span><span class="token punctuation">|</span>
</span><span class="token table-line"><span class="token punctuation">|</span><span class="token punctuation">---</span><span class="token punctuation">|</span><span class="token punctuation">---</span><span class="token punctuation">|</span><span class="token punctuation">---</span><span class="token punctuation">|</span>
</span><span class="token table-data-rows"><span class="token punctuation">|</span><span class="token table-data"> Cell 1   </span><span class="token punctuation">|</span><span class="token table-data"> Cell 2   </span><span class="token punctuation">|</span><span class="token table-data"> Cell 3   </span><span class="token punctuation">|</span>
<span class="token punctuation">|</span><span class="token table-data"> Cell 4   </span><span class="token punctuation">|</span><span class="token table-data"> Cell 5   </span><span class="token punctuation">|</span><span class="token table-data"> Cell 6   </span><span class="token punctuation">|</span></span></span></code>`,!0),a(c),k(8),i(r,l)}export{_ as default,h as metadata};
