import{a as i,f as u}from"./CzTkM99v.js";import{q as s,u as d,v as a,w as k}from"./D7a__486.js";import{h as e}from"./PSLx_Rl1.js";const g={title:"Getting Started with SvelteKit",date:"2026-03-15T00:00:00.000Z",description:"A beginner-friendly overview of SvelteKit — routing, load functions, and deploying to Vercel.",tags:["svelte","web","tutorial"],author:"Blueprint",published:!0},{title:m,date:w,description:b,tags:S,author:_,published:K}=g;var h=u('<h1>Getting Started with SvelteKit</h1> <p>SvelteKit is a full-stack framework for building web apps with Svelte. It handles routing, server-side rendering, static site generation, and more — out of the box.</p> <h2>Why SvelteKit?</h2> <ul><li><strong>Zero-config routing</strong> — files in <code>src/routes/</code> become your pages</li> <li><strong>Server + client</strong> — colocate your data fetching with your components</li> <li><strong>Adapter ecosystem</strong> — deploy to Vercel, Cloudflare, Node, or as a static site</li> <li><strong>Fast</strong> — Svelte compiles away your framework at build time</li></ul> <h2>File-based Routing</h2> <p>Every file in <code>src/routes/</code> maps to a URL:</p> <pre class="language-undefined"></pre> <p>Special file names:</p> <ul><li><code>+page.svelte</code> — the page component</li> <li><code>+page.ts</code> — load function (runs before render)</li> <li><code>+layout.svelte</code> — shared layout wrapping child routes</li> <li><code>+error.svelte</code> — custom error page</li></ul> <h2>Load Functions</h2> <p>Load functions fetch data before your component renders. They run on the server during SSR, and on the client during client-side navigation.</p> <pre class="language-typescript"></pre> <p>Access the data in your component:</p> <pre class="language-java"></pre> <h2>Deploying to Vercel</h2> <p>Install the adapter:</p> <pre class="language-bash"></pre> <p>Update <code>svelte.config.js</code>:</p> <pre class="language-javascript"></pre> <p>Then push to GitHub and connect to Vercel — it auto-detects SvelteKit and deploys with zero config.</p> <h2>What’s Next?</h2> <ul><li>Read the <a href="https://kit.svelte.dev/docs" rel="nofollow">SvelteKit docs</a></li> <li>Explore MDsveX for markdown support</li> <li>Try building a form with SvelteKit actions</li></ul> <p>SvelteKit is one of the best choices for modern web development. Give it a shot.</p>',1);function j(c){var l=h(),n=s(d(l),12);e(n,()=>`<code class="language-undefined">src/routes/
├── +page.svelte          → /
├── blog/
│   ├── +page.svelte      → /blog
│   └── [slug]/
│       └── +page.svelte  → /blog/:slug
└── about/
    └── +page.svelte      → /about</code>`,!0),a(n);var t=s(n,10);e(t,()=>`<code class="language-typescript"><span class="token comment">// src/routes/blog/+page.ts</span>
<span class="token keyword">import</span> <span class="token keyword">type</span> <span class="token punctuation">&#123;</span> PageLoad <span class="token punctuation">&#125;</span> <span class="token keyword">from</span> <span class="token string">'./$types'</span><span class="token punctuation">;</span>

<span class="token keyword">export</span> <span class="token keyword">const</span> load<span class="token operator">:</span> <span class="token function-variable function">PageLoad</span> <span class="token operator">=</span> <span class="token keyword">async</span> <span class="token punctuation">(</span><span class="token punctuation">)</span> <span class="token operator">=></span> <span class="token punctuation">&#123;</span>
  <span class="token keyword">const</span> posts <span class="token operator">=</span> <span class="token keyword">await</span> <span class="token function">fetchPosts</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
  <span class="token keyword">return</span> <span class="token punctuation">&#123;</span> posts <span class="token punctuation">&#125;</span><span class="token punctuation">;</span>
<span class="token punctuation">&#125;</span><span class="token punctuation">;</span></code>`,!0),a(t);var o=s(t,4);e(o,()=>'<code class="language-java"><span class="token class-name">System</span><span class="token punctuation">.</span>out<span class="token punctuation">.</span><span class="token function">println</span><span class="token punctuation">(</span><span class="token string">"Hello!"</span><span class="token punctuation">)</span><span class="token punctuation">;</span></code>',!0),a(o);var p=s(o,6);e(p,()=>'<code class="language-bash"><span class="token function">npm</span> <span class="token function">install</span> @sveltejs/adapter-vercel</code>',!0),a(p);var r=s(p,4);e(r,()=>`<code class="language-javascript"><span class="token keyword">import</span> adapter <span class="token keyword">from</span> <span class="token string">'@sveltejs/adapter-vercel'</span><span class="token punctuation">;</span>

<span class="token keyword">export</span> <span class="token keyword">default</span> <span class="token punctuation">&#123;</span>
  <span class="token literal-property property">kit</span><span class="token operator">:</span> <span class="token punctuation">&#123;</span> <span class="token literal-property property">adapter</span><span class="token operator">:</span> <span class="token function">adapter</span><span class="token punctuation">(</span><span class="token punctuation">)</span> <span class="token punctuation">&#125;</span>
<span class="token punctuation">&#125;</span><span class="token punctuation">;</span></code>`,!0),a(r),k(8),i(c,l)}export{j as default,g as metadata};
