import{a as e,f as p}from"./BxHpvECo.js";import{ac as t,ad as r,ae as c,ab as l}from"./BY-wSLxs.js";import{h as u}from"./BbQVLXeh.js";import{P as i}from"./CHyJysu0.js";const k={title:"PID Control",date:"2026-03-28T00:00:00.000Z",description:"A comprehensive guide to proportional, integral, and derivative control in FTC.",tags:["software","intermediate","control","completed guide"],author:"Ishaan Desai",published:!0},{title:f,date:v,description:w,tags:b,author:K,published:I}=k;var d=p('<p>PID (Proportional, Integral, Derivative) control is the most common control algorithm used in FTC for precise movements, whether it’s for a drivetrain, an arm, or a slide.</p> <div class="tuner-callout"><p><strong>Try our new full-page <a href="/simulators/pid">PID Simulator</a></strong> for a deeper understanding of PID!</p></div> <!> <h2>The Three Components</h2> <h3>1. Proportional (P)</h3> <p>The <strong>Proportional</strong> term is the simplest. It produces an output that is proportional to the current error.</p> <ul><li><strong>Error</strong> = Target - Current Position</li> <li><strong>Output</strong> = <em>K_p</em> × <strong>Error</strong></li></ul> <p>If you are far from the target, the output is large. As you get closer, the output decreases.</p> <h3>2. Integral (I)</h3> <p>The <strong>Integral</strong> term accounts for the accumulation of past errors. If the proportional term isn’t enough to reach the target (due to friction or gravity), the Integral term will slowly increase the output over time until the target is reached.</p> <ul><li><strong>Output</strong> = <em>K_p</em> × <strong>Error</strong> + <em>K_i</em> × Σ <strong>Error</strong> × <em>dt</em></li></ul> <h3>3. Derivative (D)</h3> <p>The <strong>Derivative</strong> term predicts future error based on the current rate of change. It acts as a “brake,” dampening the movement to prevent overshoot and oscillations.</p> <ul><li><strong>Output</strong> = <em>K_p</em> × <strong>Error</strong> + <em>K_d</em> × <em>d(Error)/dt</em></li></ul> <h2>Implementation in Java</h2> <p>Here is a simple PID class you can use in your FTC code:</p> <pre class="language-java"></pre> <h2>Tuning Your PID</h2> <p>Tuning is the process of finding the right values for <em>K_p</em>, <em>K_i</em>, and <em>K_d</em>.</p> <ol><li><strong>Set $K_i$ and $K_d$ to zero.</strong></li> <li><strong>Increase $K_p$</strong> until the system starts to oscillate steadily.</li> <li><strong>Increase $K_d$</strong> to dampen the oscillations and reach the target quickly without overshooting.</li> <li><strong>Increase $K_i$</strong> only if you have a steady-state error (the robot stops just before the target).</li></ol>',1);function P(o){var s=d(),n=t(r(s),4);i(n,{});var a=t(n,28);u(a,()=>`<code class="language-java"><span class="token keyword">public</span> <span class="token keyword">class</span> <span class="token class-name">PIDController</span> <span class="token punctuation">&#123;</span>
    <span class="token keyword">private</span> <span class="token keyword">double</span> <span class="token class-name">Kp</span><span class="token punctuation">,</span> <span class="token class-name">Ki</span><span class="token punctuation">,</span> <span class="token class-name">Kd</span><span class="token punctuation">;</span>
    <span class="token keyword">private</span> <span class="token keyword">double</span> target<span class="token punctuation">;</span>
    <span class="token keyword">private</span> <span class="token keyword">double</span> integralSum <span class="token operator">=</span> <span class="token number">0</span><span class="token punctuation">;</span>
    <span class="token keyword">private</span> <span class="token keyword">double</span> lastError <span class="token operator">=</span> <span class="token number">0</span><span class="token punctuation">;</span>
    <span class="token keyword">private</span> <span class="token class-name">ElapsedTime</span> timer <span class="token operator">=</span> <span class="token keyword">new</span> <span class="token class-name">ElapsedTime</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">;</span>

    <span class="token keyword">public</span> <span class="token class-name">PIDController</span><span class="token punctuation">(</span><span class="token keyword">double</span> <span class="token class-name">Kp</span><span class="token punctuation">,</span> <span class="token keyword">double</span> <span class="token class-name">Ki</span><span class="token punctuation">,</span> <span class="token keyword">double</span> <span class="token class-name">Kd</span><span class="token punctuation">)</span> <span class="token punctuation">&#123;</span>
        <span class="token class-name"><span class="token namespace">this<span class="token punctuation">.</span></span>Kp</span> <span class="token operator">=</span> <span class="token class-name">Kp</span><span class="token punctuation">;</span>
        <span class="token class-name"><span class="token namespace">this<span class="token punctuation">.</span></span>Ki</span> <span class="token operator">=</span> <span class="token class-name">Ki</span><span class="token punctuation">;</span>
        <span class="token class-name"><span class="token namespace">this<span class="token punctuation">.</span></span>Kd</span> <span class="token operator">=</span> <span class="token class-name">Kd</span><span class="token punctuation">;</span>
    <span class="token punctuation">&#125;</span>

    <span class="token keyword">public</span> <span class="token keyword">double</span> <span class="token function">calculate</span><span class="token punctuation">(</span><span class="token keyword">double</span> currentPosition<span class="token punctuation">)</span> <span class="token punctuation">&#123;</span>
        <span class="token keyword">double</span> error <span class="token operator">=</span> target <span class="token operator">-</span> currentPosition<span class="token punctuation">;</span>
        <span class="token keyword">double</span> derivative <span class="token operator">=</span> <span class="token punctuation">(</span>error <span class="token operator">-</span> lastError<span class="token punctuation">)</span> <span class="token operator">/</span> timer<span class="token punctuation">.</span><span class="token function">seconds</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
        integralSum <span class="token operator">+=</span> error <span class="token operator">*</span> timer<span class="token punctuation">.</span><span class="token function">seconds</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">;</span>

        <span class="token comment">// Anti-windup for the integral term</span>
        <span class="token keyword">if</span> <span class="token punctuation">(</span><span class="token class-name">Math</span><span class="token punctuation">.</span><span class="token function">abs</span><span class="token punctuation">(</span>error<span class="token punctuation">)</span> <span class="token operator">&lt;</span> <span class="token number">1</span><span class="token punctuation">)</span> <span class="token punctuation">&#123;</span> <span class="token comment">// Threshold</span>
             integralSum <span class="token operator">=</span> <span class="token number">0</span><span class="token punctuation">;</span>
        <span class="token punctuation">&#125;</span>

        <span class="token keyword">double</span> output <span class="token operator">=</span> <span class="token punctuation">(</span><span class="token class-name">Kp</span> <span class="token operator">*</span> error<span class="token punctuation">)</span> <span class="token operator">+</span> <span class="token punctuation">(</span><span class="token class-name">Ki</span> <span class="token operator">*</span> integralSum<span class="token punctuation">)</span> <span class="token operator">+</span> <span class="token punctuation">(</span><span class="token class-name">Kd</span> <span class="token operator">*</span> derivative<span class="token punctuation">)</span><span class="token punctuation">;</span>

        lastError <span class="token operator">=</span> error<span class="token punctuation">;</span>
        timer<span class="token punctuation">.</span><span class="token function">reset</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">;</span>

        <span class="token keyword">return</span> output<span class="token punctuation">;</span>
    <span class="token punctuation">&#125;</span>

    <span class="token keyword">public</span> <span class="token keyword">void</span> <span class="token function">setTarget</span><span class="token punctuation">(</span><span class="token keyword">double</span> target<span class="token punctuation">)</span> <span class="token punctuation">&#123;</span>
        <span class="token keyword">this</span><span class="token punctuation">.</span>target <span class="token operator">=</span> target<span class="token punctuation">;</span>
    <span class="token punctuation">&#125;</span>
<span class="token punctuation">&#125;</span></code>`,!0),c(a),l(6),e(o,s)}export{P as default,k as metadata};
