name: Discord Notification

on:
  push:

jobs:
  send:
    runs-on: ubuntu-latest

    steps:
      - name: Send message
        run: |
          curl -H "Content-Type: application/json" \
          -d "{\"content\": \"New push to Blueprint\"}" \
          ${{ secrets.DISCORD_WEBHOOK }}
